name: Deploy Garimpo Chique 🚀

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositório
        uses: actions/checkout@v3

      - name: 🟢 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Instalar dependências
        run: |
          cd backend
          npm install

      - name: 🧪 (Opcional) Rodar testes
        run: |
          cd backend
          npm test || echo "⚠️ Nenhum teste configurado"

      - name: 📁 Copiar frontend para backend/public
        run: |
          mkdir -p backend/public
          cp -r frontend/* backend/public/

      - name: 🚀 Deploy para Render
        uses: johnbeynon/render-deploy-action@v1
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
