Backlog / Planejamento
     ↓
Criar branch feature
     ↓
Desenvolver localmente (frontend + backend)
     ↓
Testes locais / QA
     ↓
Abrir Pull Request → Revisão
     ↓
Merge para main
     ↓
Pipeline CI/CD (testes, build)
     ↓
Deploy para produção
     ↓
Monitoramento / feedback → volta para backlog

